CREATE TABLE "HT_REGRESSION_QA"."ADDRESS" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"ADDRESS1" VARCHAR2(80 CHAR), 
	"ADDRESS2" VARCHAR2(80 CHAR), 
	"ADDRESS3" VARCHAR2(80 CHAR), 
	"ADDRESS4" VARCHAR2(80 CHAR), 
	"ADDRESS5" VARCHAR2(80 CHAR), 
	"CITY" VARCHAR2(80 CHAR), 
	"STATE" VARCHAR2(80 CHAR), 
	"ZIP" VARCHAR2(80 CHAR), 
	"COUNTRY" VARCHAR2(80 CHAR), 
	"DISPLAY" VARCHAR2(80 CHAR), 
	"CODE" VARCHAR2(20 CHAR), 
	"TYPE" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"LAST_ERP_DATE" DATE, 
	"IS_ASSIGNED" NUMBER NOT NULL ENABLE, 
	"ERP_ACCOUNT_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."ASSEMBLY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PROGRAM_OID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "ASSEMBLY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."ASSEMBLY_DIST_MAPPING" 
   (	"ASSEMBLY_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "ASSEMBLY_DIST_MAPPING_UK1" UNIQUE ("ASSEMBLY_OID", "DISTRIBUTOR_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";
