CREATE TABLE "HT_REGRESSION_QA"."GEOGRAPHY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	 CONSTRAINT "GEOGRAPHY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "GEOGRAPHY_UK1" UNIQUE ("SFDC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."GROUP_MEMBER" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"USER_GROUP_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "GROUP_MEMBER_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "GROUP_MEMBER_UK1" UNIQUE ("USER_GROUP_OID", "PRO_USER_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."GROUP_TRANS_MAPPING" 
   (	"USER_GROUP_OID" NUMBER NOT NULL ENABLE, 
	"VALUE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "GROUP_TRANS_MAPPING_UK1" UNIQUE ("USER_GROUP_OID", "VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"PART_EXT" VARCHAR2(80 CHAR), 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "INVENTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "INVENTORY_UK1" UNIQUE ("PART_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_BONDED" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"CEM_FLAG" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INVENTORY_BONDED_UK1" UNIQUE ("INVENTORY_OID", "CUSTOMER_OID", "CEM_FLAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "INVENTORY_BONDED_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_BUCKET" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"END_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"PRO_ORDER_OID" NUMBER NOT NULL ENABLE, 
	"ORDER_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"ORDER_SCHEDULE_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"ORIGINAL_QTY" NUMBER NOT NULL ENABLE, 
	"AVAILABLE_QTY" NUMBER NOT NULL ENABLE, 
	"RESERVED_QTY" NUMBER NOT NULL ENABLE, 
	"SHIP_DATE" DATE NOT NULL ENABLE, 
	"AVAILABLE_DATE" DATE NOT NULL ENABLE, 
	"CURRENT_COST" NUMBER(38,6) NOT NULL ENABLE, 
	"ORIG_ACQUISITION_COST" NUMBER(38,6) NOT NULL ENABLE, 
	"MANUFACTURER_COST" NUMBER(38,6), 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"AGREEMENT_TYPE" VARCHAR2(80 CHAR), 
	"AGREEMENT_OID" NUMBER NOT NULL ENABLE, 
	"ACQUISITION_INVOICE_NUM" VARCHAR2(80 CHAR), 
	"TAX_RATE" NUMBER(38,15), 
	"SHIP_FROM" VARCHAR2(80 CHAR), 
	"SHIP_TO" VARCHAR2(80 CHAR), 
	"IS_DEBITABLE" NUMBER NOT NULL ENABLE, 
	"IS_PRICE_PROTECT" NUMBER NOT NULL ENABLE, 
	"CAN_ROTATE" NUMBER NOT NULL ENABLE, 
	"NCNR" NUMBER NOT NULL ENABLE, 
	"IS_SCRAP" NUMBER NOT NULL ENABLE, 
	"DEFERRED_REVENUE_FLAG" NUMBER NOT NULL ENABLE, 
	"PARENT_INVENTORY_BUCKET_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_TABLE_DEFINITION_OID" NUMBER NOT NULL ENABLE, 
	"APPLY_RULE" NUMBER NOT NULL ENABLE, 
	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"INV_BKT_RULE_ACTION_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "INVENTORY_BUCKET_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_BUCKET_ADJ" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_BUCKET_OID" NUMBER NOT NULL ENABLE, 
	"ADJUSTMENT_TYPE" VARCHAR2(80 CHAR), 
	"ADJUSTMENT_NUM" NUMBER, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"END_QUANTITY" NUMBER NOT NULL ENABLE, 
	"END_PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"RESERVED_QTY" NUMBER NOT NULL ENABLE, 
	"UPDATED_BY_OID" NUMBER NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(1024 CHAR), 
	"REASON_CODE" VARCHAR2(80 CHAR), 
	 CONSTRAINT "INVENTORY_BUCKET_ADJ_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_BUCKET_RULE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"RULE_NAME" VARCHAR2(80 CHAR), 
	"PRIORITY" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(15 CHAR), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"EXPIRE_DATE" DATE NOT NULL ENABLE, 
	"END_CUST_FIELD_TYPE" NUMBER NOT NULL ENABLE, 
	"END_CUST_IS_APPROVED" NUMBER, 
	"END_CUST_GEOGRAPHY_OID" NUMBER NOT NULL ENABLE, 
	"END_CUST_TYPE" VARCHAR2(20 CHAR), 
	"END_CUST_COUNTRY_TYPE_OID" NUMBER NOT NULL ENABLE, 
	"END_CUST_COUNTRY" VARCHAR2(80 CHAR), 
	"PRICING_REGION_OID" NUMBER NOT NULL ENABLE, 
	"IS_DEBITABLE" NUMBER, 
	"IS_PRICE_PROTECT" NUMBER, 
	"CAN_ROTATE" NUMBER, 
	"IS_SCRAP" NUMBER, 
	"DEFERRED_REVENUE_FLAG" NUMBER, 
	"IS_INV_NCNR" NUMBER, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"IS_NCNR" NUMBER, 
	"IS_SOLE_SOURCE" NUMBER, 
	"IS_REGISTERABLE" NUMBER, 
	"PART_FIELD_TYPE" NUMBER NOT NULL ENABLE, 
	"SALES_CHANNEL" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"DISTI_CORP_ID_OID" NUMBER NOT NULL ENABLE, 
	"AGREEMENT_TYPE" VARCHAR2(80 CHAR), 
	"SEGMENT_OID" NUMBER NOT NULL ENABLE, 
	"AVAILABLE_DATE_BEFORE" DATE, 
	"AVAILABLE_DATE_AFTER" DATE, 
	"SHIP_DATE_BEFORE" DATE, 
	"SHIP_DATE_AFTER" DATE, 
	"SUBMITTED_BY_OID" NUMBER NOT NULL ENABLE, 
	"IS_GENERIC" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "INVENTORY_BUCKET_RULE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_COMMITTED" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"COMMITTED_DATE" DATE NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"ORDER_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"PLACED" NUMBER NOT NULL ENABLE, 
	"INVENTORY_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"INVENTORY_ITEM_BUCKET_OID" NUMBER NOT NULL ENABLE, 
	"INVENTORY_BONDED_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INVENTORY_COMMITTED_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_DISPLAY_BUCKET" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"BUCKET_NUM" NUMBER NOT NULL ENABLE, 
	"START_DAY" NUMBER NOT NULL ENABLE, 
	"IS_DIRECT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INVENTORY_DISPLAY_BUCKET_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_OID" NUMBER NOT NULL ENABLE, 
	"QAS" NUMBER NOT NULL ENABLE, 
	"QOH" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"REPORTED_DISTI_COST" NUMBER(38,6) NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"WAREHOUSE_OID" NUMBER NOT NULL ENABLE, 
	"REFRESH_DATE" DATE, 
	"STATUS" VARCHAR2(80 CHAR), 
	"INVENTORY_TRACKING_OID" NUMBER NOT NULL ENABLE, 
	"BAD_RECORD_OID" NUMBER NOT NULL ENABLE, 
	"ORIG_INVENTORY_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"IMPORT_OID" NUMBER NOT NULL ENABLE, 
	"REPORTED_AT_ROOT" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "INVENTORY_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_ITEM_BUCKET" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"AVAILABLE_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "INVENTORY_ITEM_BUCKET_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_REPORTED_INFO" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"WAREHOUSE_OID" NUMBER NOT NULL ENABLE, 
	"REFRESH_DATE" DATE, 
	 CONSTRAINT "INVENTORY_REPORTED_INFO_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INVENTORY_TRACKING" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(256 CHAR), 
	"RECORD_NUM" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR" VARCHAR2(1024 CHAR), 
	"MPN" VARCHAR2(1024 CHAR), 
	"QAS" VARCHAR2(1024 CHAR), 
	"QOH" VARCHAR2(1024 CHAR), 
	"REPORTED_DISTI_COST" VARCHAR2(1024 CHAR), 
	"CURRENCY_CODE" VARCHAR2(80 CHAR), 
	"WAREHOUSE_NAME" VARCHAR2(1024 CHAR), 
	"WAREHOUSE_LOCATION" VARCHAR2(1024 CHAR), 
	"ADDRESS1" VARCHAR2(1024 CHAR), 
	"ADDRESS2" VARCHAR2(1024 CHAR), 
	"CITY" VARCHAR2(1024 CHAR), 
	"STATE" VARCHAR2(1024 CHAR), 
	"ZIP" VARCHAR2(1024 CHAR), 
	"COUNTRY" VARCHAR2(1024 CHAR), 
	"INVENTORY_DATE" VARCHAR2(1024 CHAR), 
	"STATUS" VARCHAR2(80 CHAR), 
	"INVENTORY_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"IMPORT_OID" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATED_BY_OID" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATED_ON" DATE, 
	"COMMENTS" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "INVENTORY_TRACKING_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_ACTION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"FROM_AGE" NUMBER NOT NULL ENABLE, 
	"TO_AGE" NUMBER NOT NULL ENABLE, 
	"IS_DEBITABLE" NUMBER, 
	"IS_PRICE_PROTECT" NUMBER, 
	"CAN_ROTATE" NUMBER, 
	"IS_SCRAP" NUMBER, 
	"IS_INV_NCNR" NUMBER, 
	"DEFERRED_REVENUE_FLAG" NUMBER, 
	"APPLY_RULE" NUMBER, 
	"CUSTOM_CLASS" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "INV_BKT_RULE_ACTION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_ATT_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"PART_ATTRIBUTE_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_ATT_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "PART_ATTRIBUTE_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_CUST_PART_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_PART_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_CUST_PART_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "CUSTOMER_PART_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_END_ACC_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"VALUE" VARCHAR2(80 CHAR), 
	 CONSTRAINT "INV_BKT_RULE_END_ACC_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_END_CAT_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"CUST_CATEGORY_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_END_CAT_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "CUST_CATEGORY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_END_CUST_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_END_CUST_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "CUSTOMER_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR), 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"IS_SUMMARY" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_PART_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_PART_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "PART_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_PF_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_PF_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "PRODUCT_FAMILY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_PRICE_CAT_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_CATEGORY_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_PRICE_CAT_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "PRICE_CATEGORY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_ROOT_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"VALUE" VARCHAR2(80 CHAR), 
	 CONSTRAINT "INV_BKT_RULE_ROOT_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_BKT_RULE_SF_MAP" 
   (	"INVENTORY_BUCKET_RULE_OID" NUMBER NOT NULL ENABLE, 
	"SUB_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_BKT_RULE_SF_MAP_UK1" UNIQUE ("INVENTORY_BUCKET_RULE_OID", "SUB_FAMILY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_RECON_ADJ_REASON_CODE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"REASON_CODE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"REASON_ORDER" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "INV_RECON_ADJ_REASON_CODE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_SNAPSHOT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"PERIOD_DATE" DATE NOT NULL ENABLE, 
	"RECONCILIATION_DATE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "INV_SNAPSHOT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."INV_SNAPSHOT_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INV_SNAPSHOT_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"PRIOR_CALC_QOH" NUMBER NOT NULL ENABLE, 
	"SHIPMENT_QTY" NUMBER NOT NULL ENABLE, 
	"POS_QTY" NUMBER NOT NULL ENABLE, 
	"ADJUSTMENT_QTY" NUMBER NOT NULL ENABLE, 
	"CALC_QOH" NUMBER NOT NULL ENABLE, 
	"IN_TRANSIT" NUMBER NOT NULL ENABLE, 
	"IN_TRANSIT_ADJUSTED" NUMBER NOT NULL ENABLE, 
	"NET_COH" NUMBER NOT NULL ENABLE, 
	"REPORTED_QOH" NUMBER NOT NULL ENABLE, 
	"DISCREPANCY" NUMBER NOT NULL ENABLE, 
	"DISCREPANCY_PERCENTAGE" NUMBER(38,6) NOT NULL ENABLE, 
	"TOTAL_DISCREPANCY" NUMBER NOT NULL ENABLE, 
	"CALC_QOH_PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"CALC_QOH_VALUE" NUMBER(38,6) NOT NULL ENABLE, 
	"REP_CALC_QOH_PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"REP_CALC_QOH_VALUE" NUMBER(38,6) NOT NULL ENABLE, 
	"DISCREPANCY_VALUE" NUMBER(38,6) NOT NULL ENABLE, 
	"DISCREPANCY_VALUE_PERCENT" NUMBER(38,6) NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "INV_SNAPSHOT_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."KIT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR), 
	"DESCRIPTION" VARCHAR2(1024 CHAR), 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"IS_KIT" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MIN" NUMBER NOT NULL ENABLE, 
	"MULT" NUMBER NOT NULL ENABLE, 
	"IS_DESC_OVERRIDEN" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "KIT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."KIT_COMPONENT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"KIT_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"ITEM_NUM" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "KIT_COMPONENT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "KIT_COMPONENT_UK1" UNIQUE ("SFDC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."KIT_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"KIT_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "KIT_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";
