CREATE TABLE "HT_REGRESSION_QA"."PART" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"MPN" VARCHAR2(80 CHAR), 
	"SMARTPART" VARCHAR2(80 CHAR), 
	"DESCRIPTION" VARCHAR2(256 CHAR), 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"MIN" NUMBER NOT NULL ENABLE, 
	"MULT" NUMBER NOT NULL ENABLE, 
	"LEADTIME" NUMBER NOT NULL ENABLE, 
	"LEADTIME_UNITS" VARCHAR2(80 CHAR), 
	"INVENTORY" NUMBER NOT NULL ENABLE, 
	"INVENTORY_DATE" DATE, 
	"UOM_OID" NUMBER NOT NULL ENABLE, 
	"REGISTER" NUMBER NOT NULL ENABLE, 
	"SOLE_SOURCE" NUMBER NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"CAN_SAMPLE" NUMBER NOT NULL ENABLE, 
	"NCNR" NUMBER NOT NULL ENABLE, 
	"PART_CLASS" VARCHAR2(20 CHAR), 
	"PRICE_CATEGORY_OID" NUMBER, 
	"CAN_SEARCH" NUMBER NOT NULL ENABLE, 
	"CAN_QUOTE" NUMBER NOT NULL ENABLE, 
	"CAN_ORDER" NUMBER NOT NULL ENABLE, 
	"PRODUCT_DIVISION" VARCHAR2(80 CHAR), 
	"CAN_OPP" NUMBER NOT NULL ENABLE, 
	"CAN_REGISTER" NUMBER NOT NULL ENABLE, 
	"CAN_DEBIT" NUMBER NOT NULL ENABLE, 
	"SUB_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"CAN_ROTATE" NUMBER NOT NULL ENABLE, 
	"CAN_FORECAST" NUMBER NOT NULL ENABLE, 
	"PREFIX" VARCHAR2(80 CHAR), 
	"ROOT" VARCHAR2(80 CHAR), 
	"SUFFIX" VARCHAR2(80 CHAR), 
	"IS_ROOT" NUMBER NOT NULL ENABLE, 
	"TRANS_LINKAGE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"REG_LINKAGE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"CAN_MERGE_CPN" NUMBER NOT NULL ENABLE, 
	"CAN_MERGE_END_CUSTOMER" NUMBER NOT NULL ENABLE, 
	"CAN_CONTRACT" NUMBER NOT NULL ENABLE, 
	"IS_BASE" NUMBER NOT NULL ENABLE, 
	"BASE_PART_OID" NUMBER NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"TYPE" NUMBER NOT NULL ENABLE, 
	"CAN_KIT" NUMBER NOT NULL ENABLE, 
	"ROOT_PART_OID" NUMBER NOT NULL ENABLE, 
	"CAN_REBATE" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "PART_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PART_UK1" UNIQUE ("MPN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PART_UK2" UNIQUE ("SFDC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_ALIAS" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"PN" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PART_ALIAS_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PART_ALIAS_UK1" UNIQUE ("PN", "DISTRIBUTOR_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_APPLICATION_GROUP_MAPPING" 
   (	"PART_OID" NUMBER NOT NULL ENABLE, 
	"APPLICATION_GROUP_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRT_PPLCTN_GRP_MPPNG_UK1" UNIQUE ("PART_OID", "APPLICATION_GROUP_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_ATTRIBUTE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_ATTRIBUTE_HEADER_OID" NUMBER NOT NULL ENABLE, 
	"SELECTOR_VALUE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"ATTRIBUTE_VALUE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80 CHAR), 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PART_ATTRIBUTE_UK1" UNIQUE ("SFDC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PART_ATTRIBUTE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_ATTRIBUTE_HEADER" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"SHOW_IN_DETAIL" NUMBER NOT NULL ENABLE, 
	"SHOW_IN_POPUP" NUMBER NOT NULL ENABLE, 
	"SHOW_IN_SEARCH" NUMBER NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PART_ATTRIBUTE_HEADER_UK1" UNIQUE ("SFDC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PART_ATTRIBUTE_HEADER_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_ATTRIB_MAPPING" 
   (	"PART_OID" NUMBER NOT NULL ENABLE, 
	"PART_ATTRIBUTE_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PART_ATTRIB_MAPPING_UK1" UNIQUE ("PART_OID", "PART_ATTRIBUTE_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_CROSS_MAPPING" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"COMP_PART_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"EQUIVALENCE" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PART_CROSS_MAPPING_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_DATASHEET" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"URL" VARCHAR2(256 CHAR) NOT NULL ENABLE, 
	"HIDDEN" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PART_DATASHEET_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PART_WORD" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"WORD" VARCHAR2(256 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PART_WORD_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PART_WORD_UK1" UNIQUE ("PART_OID", "WORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PF_USER_CAP_MAPPING" 
   (	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"USER_CAPABILITY_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PF_USER_CAP_MAPPING_UK1" UNIQUE ("PRO_USER_OID", "USER_CAPABILITY_OID", "PRODUCT_FAMILY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PF_USER_MAPPING" 
   (	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PF_USER_MAPPING_UK1" UNIQUE ("PRO_USER_OID", "PRODUCT_FAMILY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_DATA" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DISTI_BRANCH_ORG_OID" NUMBER NOT NULL ENABLE, 
	"EXPIRE_DATE" DATE, 
	"REMAINING_QUANTITY" NUMBER, 
	"CR_FLAG" VARCHAR2(80 CHAR), 
	"DISTRIBUTOR" VARCHAR2(80 CHAR), 
	"DEBIT_NUM" VARCHAR2(80 CHAR), 
	"CUSTOMER_NAME" VARCHAR2(80 CHAR), 
	"LOCATION" VARCHAR2(80 CHAR), 
	"CITY" VARCHAR2(80 CHAR), 
	"STATE" VARCHAR2(80 CHAR), 
	"ZIP" VARCHAR2(80 CHAR), 
	"COUNTRY" VARCHAR2(80 CHAR), 
	"MPN" VARCHAR2(80 CHAR), 
	"POS_DISTI_RESALE" NUMBER(38,6), 
	"POS_DISTI_COST" NUMBER(38,6), 
	"POS_DISTI_BOOK_COST" NUMBER(38,6), 
	"POS_DISTI_BRANCH_CODE" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_NUM" VARCHAR2(80 CHAR), 
	"STATUS" VARCHAR2(80 CHAR), 
	"LAST_EXPORT_DATE" DATE, 
	"SHIP_QTY" NUMBER, 
	"SHIP_DATE" DATE, 
	"INVOICE_NUM" VARCHAR2(80 CHAR), 
	"ORIGINAL_INVOICE_NUM" VARCHAR2(80 CHAR), 
	"ACQUISITION_INVOICE_NUM" VARCHAR2(80 CHAR), 
	"CLAIM_NUM" VARCHAR2(80 CHAR), 
	"MFR_TRACKING_NUM" VARCHAR2(80 CHAR), 
	"REJECT_CODE" VARCHAR2(80 CHAR), 
	"POS_MONTH" DATE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"END_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"SEGMENT_OID" NUMBER NOT NULL ENABLE, 
	"IS_SEGMENT_OVERRIDE" NUMBER NOT NULL ENABLE, 
	"DISTI_RESALE_DENOM" VARCHAR2(80 CHAR), 
	"DISTI_RESALE_CURRENCY_CODE" VARCHAR2(80 CHAR), 
	"DISTI_RESALE_EXCHANGE_RATE" VARCHAR2(80 CHAR), 
	"DISTI_COST_DENOM" VARCHAR2(80 CHAR), 
	"DISTI_COST_CURRENCY_CODE" VARCHAR2(80 CHAR), 
	"DISTI_COST_EXCHANGE_RATE" VARCHAR2(80 CHAR), 
	"DBC_DENOM" VARCHAR2(80 CHAR), 
	"DBC_CURRENCY_CODE" VARCHAR2(80 CHAR), 
	"DBC_EXCHANGE_RATE" VARCHAR2(80 CHAR), 
	"PART_EXT" VARCHAR2(80 CHAR), 
	"ORIGINAL_POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"END_CUSTOMER_NAME" VARCHAR2(80 CHAR), 
	"END_CUST_LOCATION" VARCHAR2(80 CHAR), 
	"END_CUST_CITY" VARCHAR2(80 CHAR), 
	"END_CUST_STATE" VARCHAR2(80 CHAR), 
	"END_CUST_ZIP" VARCHAR2(80 CHAR), 
	"END_CUST_COUNTRY" VARCHAR2(80 CHAR), 
	"CPN" VARCHAR2(80 CHAR), 
	"CUST_PART_MAPPING_OID" NUMBER NOT NULL ENABLE, 
	"WAS_POS_POSTED" NUMBER NOT NULL ENABLE, 
	"WAS_COMMISSION_POSTED" NUMBER NOT NULL ENABLE, 
	"POS_NUM" VARCHAR2(80 CHAR), 
	"IS_DUPE" NUMBER NOT NULL ENABLE, 
	"DEBIT_ITEM_NUM" NUMBER NOT NULL ENABLE, 
	"DESIGN_PART_MAPPING_OID" NUMBER NOT NULL ENABLE, 
	"OPP_REG_NUM" VARCHAR2(80 CHAR), 
	"POS_TRACKING_OID" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(256 CHAR), 
	"RECORD_NUM" NUMBER, 
	"NO_INVENTORY" NUMBER NOT NULL ENABLE, 
	"REVERSAL_STATUS" VARCHAR2(80 CHAR), 
	"REVERSAL_POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"QUOTE_NUM" VARCHAR2(80 CHAR), 
	"QUOTE_ITEM_NUM" VARCHAR2(80 CHAR), 
	"CALC_DISTI_BOOK_COST" NUMBER(38,6), 
	"CALC_DISTI_BOOK_COST_SOURCE" VARCHAR2(80 CHAR), 
	"CALC_DISTI_BOOK_COST_OID" NUMBER NOT NULL ENABLE, 
	"CALC_DBC_DENOM" NUMBER(38,6), 
	"CALC_DBC_CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"CALC_DBC_EXCHANGE_RATE" NUMBER(38,15), 
	"ACCEPTED_ON" DATE, 
	"ACCEPTED_BY" VARCHAR2(80 CHAR), 
	"CR_ACCEPTED_ON" DATE, 
	"CR_ACCEPTED_BY" VARCHAR2(80 CHAR), 
	"REJECTED_ON" DATE, 
	"REJECTED_BY" VARCHAR2(80 CHAR), 
	"LINKED_POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"RETURN_QTY" NUMBER NOT NULL ENABLE, 
	"IMPORT_OID" NUMBER NOT NULL ENABLE, 
	"LINKED_BUNDLE_OID" NUMBER NOT NULL ENABLE, 
	"BUCKET_PART_OID" NUMBER NOT NULL ENABLE, 
	"CREDIT_MEMO_IMPORT_DATE" DATE, 
	"CREDIT_MEMO_ITEM_NUM" VARCHAR2(80 CHAR), 
	"COMMENTS" VARCHAR2(1024 CHAR), 
	"REASON_CODE_OID" NUMBER NOT NULL ENABLE, 
	"DEBIT_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"INVOICE_LINE_NUM" VARCHAR2(80 CHAR), 
	"ORIGINAL_INVOICE_LINE_NUM" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_INVOICE_DATE" DATE, 
	"CREDIT_MEMO_EXPORT_DATE" DATE, 
	"CREDIT_MEMO_AMOUNT" NUMBER(38,6), 
	"CUST_CDM_ID" VARCHAR2(80 CHAR), 
	"END_CUST_CDM_ID" VARCHAR2(80 CHAR), 
	"FORMAT_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "POS_DATA_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_DATA_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "POS_DATA_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_ERROR_OVERRIDE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"COLUMN_KEY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"ERROR_CODE" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"USER_CAPABILITY_OID" NUMBER NOT NULL ENABLE, 
	"IS_CUSTOM" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "POS_ERROR_OVERRIDE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_INFO" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"BAD_RECORD_OID" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_SHIP_QTY" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_SHIP_DATE" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_DISTI_COST" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_DISTI_RESALE" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_DISTI_BOOK_COST" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_DEBIT_ITEM" NUMBER NOT NULL ENABLE, 
	"SAVE_PART_ALIAS" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_MPN" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_CUSTOMER" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_END_CUSTOMER" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_INVOICE_NUM" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_TRANS_CODE" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_OLD_SHIP_DATE" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_DUPE" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_NO_INVENTORY" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_OPP_REG_NUM" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_QUOTE_ITEM" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_BUCKET" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_INV_NOT_DEBITABLE" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_EARLY_SHIP_DATE_INV" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_QUOTE_NUM_INV" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_END_CUST_INV" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_END_CUST_HRCHY_INV" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_ACQ_INVOICE_NUM_INV" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_FUTURE_SHIP_DATE" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_CRR_HAS_IN_SUFF_CR" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_CANCELLED_ITEM" NUMBER NOT NULL ENABLE, 
	"OVERRIDE_REJECTED_ITEM" NUMBER NOT NULL ENABLE, 
	"DATA1" VARCHAR2(1024 CHAR), 
	"DATA2" VARCHAR2(1024 CHAR), 
	"DATA3" VARCHAR2(1024 CHAR), 
	"DATA4" VARCHAR2(1024 CHAR), 
	"DATA5" VARCHAR2(1024 CHAR), 
	"DATA6" VARCHAR2(1024 CHAR), 
	"DATA7" VARCHAR2(1024 CHAR), 
	"DATA8" VARCHAR2(1024 CHAR), 
	"DATA9" VARCHAR2(1024 CHAR), 
	"DATA10" VARCHAR2(1024 CHAR), 
	"DATA11" VARCHAR2(1024 CHAR), 
	"DATA12" VARCHAR2(1024 CHAR), 
	"DATA13" VARCHAR2(1024 CHAR), 
	"DATA14" VARCHAR2(1024 CHAR), 
	"DATA15" VARCHAR2(1024 CHAR), 
	"DATA16" VARCHAR2(1024 CHAR), 
	"DATA17" VARCHAR2(1024 CHAR), 
	"DATA18" VARCHAR2(1024 CHAR), 
	"DATA19" VARCHAR2(1024 CHAR), 
	"DATA20" VARCHAR2(1024 CHAR), 
	"DATA21" VARCHAR2(1024 CHAR), 
	"DATA22" VARCHAR2(1024 CHAR), 
	"DATA23" VARCHAR2(1024 CHAR), 
	"DATA24" VARCHAR2(1024 CHAR), 
	"DATA25" VARCHAR2(1024 CHAR), 
	"DATA26" VARCHAR2(1024 CHAR), 
	"DATA27" VARCHAR2(1024 CHAR), 
	"DATA28" VARCHAR2(1024 CHAR), 
	"DATA29" VARCHAR2(1024 CHAR), 
	"DATA30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "POS_INFO_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_REBATE_DATA" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"DISTI_BRANCH_OID" NUMBER NOT NULL ENABLE, 
	"INVOICE_NUM" VARCHAR2(80 CHAR), 
	"CR_FLAG" VARCHAR2(10 CHAR), 
	"SHIP_DATE" DATE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"END_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"DISTI_COST" NUMBER(38,6) NOT NULL ENABLE, 
	"DISTI_RESALE" NUMBER(38,6) NOT NULL ENABLE, 
	"IS_EXPORTED" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"POS_TXN_GROUP_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR), 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "POS_REBATE_DATA_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_RETURN_POS_MAPPING" 
   (	"POS_DATA_RETURN_OID" NUMBER NOT NULL ENABLE, 
	"ORIGINAL_POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "POS_RETURN_POS_MAPPING_UK1" UNIQUE ("POS_DATA_RETURN_OID", "ORIGINAL_POS_DATA_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_TO_PROCESS" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PROCESSING_START_TIME" DATE, 
	"POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"DESIGN_REG_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"SCHED_DATE" DATE, 
	"SCHED_QUANTITY" NUMBER NOT NULL ENABLE, 
	"SCHEDULE_STATUS" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR), 
	"MERGE_NEEDED" NUMBER NOT NULL ENABLE, 
	"REJECT_ALL_ITEMS" NUMBER NOT NULL ENABLE, 
	"IS_CR" NUMBER NOT NULL ENABLE, 
	"DISTI_COST" NUMBER(38,6), 
	"DISTI_RESALE" NUMBER(38,6), 
	"LINE_QTY" NUMBER NOT NULL ENABLE, 
	"TRANS_CODE" VARCHAR2(80 CHAR) DEFAULT '''-''' NOT NULL ENABLE, 
	"POS_JUST_POSTED" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"ORIG_DISTI_COST" NUMBER(38,6), 
	"ORIG_DISTI_RESALE" NUMBER(38,6), 
	 CONSTRAINT "POS_TO_PROCESS_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."POS_TRACKING" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(256 CHAR) NOT NULL ENABLE, 
	"RECORD_NUM" NUMBER NOT NULL ENABLE, 
	"POS_MONTH" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"REJECT_CODE" VARCHAR2(80 CHAR), 
	"POS_DATA_OID" NUMBER NOT NULL ENABLE, 
	"TRANS_CODE" VARCHAR2(80 CHAR), 
	"DISTRIBUTOR" VARCHAR2(80 CHAR), 
	"DEBIT_NUM" VARCHAR2(80 CHAR), 
	"DEBIT_ITEM_NUM" VARCHAR2(80 CHAR), 
	"CUST_NAME" VARCHAR2(80 CHAR), 
	"CUST_DISTI_ACCT_NUM" VARCHAR2(80 CHAR), 
	"CUST_CITY" VARCHAR2(80 CHAR), 
	"CUST_STATE" VARCHAR2(80 CHAR), 
	"CUST_ZIP" VARCHAR2(80 CHAR), 
	"CUST_COUNTRY" VARCHAR2(80 CHAR), 
	"MPN" VARCHAR2(80 CHAR), 
	"PART_EXT" VARCHAR2(80 CHAR), 
	"CPN" VARCHAR2(80 CHAR), 
	"SHIP_QTY" VARCHAR2(80 CHAR), 
	"SHIP_DATE" VARCHAR2(80 CHAR), 
	"DISTI_RESALE" VARCHAR2(80 CHAR), 
	"DISTI_RESALE_DENOM" VARCHAR2(80 CHAR), 
	"DISTI_RESALE_CURRENCY_CODE" VARCHAR2(80 CHAR), 
	"DISTI_RESALE_EXCHANGE_RATE" VARCHAR2(80 CHAR), 
	"DISTI_COST" VARCHAR2(80 CHAR), 
	"DISTI_COST_DENOM" VARCHAR2(80 CHAR), 
	"DISTI_COST_CURRENCY_CODE" VARCHAR2(80 CHAR), 
	"DISTI_COST_EXCHANGE_RATE" VARCHAR2(80 CHAR), 
	"DISTI_INVOICE_NUM" VARCHAR2(80 CHAR), 
	"ORIGINAL_INVOICE_NUM" VARCHAR2(80 CHAR), 
	"ACQUISITION_INVOICE_NUM" VARCHAR2(80 CHAR), 
	"DISTI_BOOK_COST" VARCHAR2(80 CHAR), 
	"DISTI_BOOK_COST_DENOM" VARCHAR2(80 CHAR), 
	"DISTI_BOOK_COST_CURRENCY_CODE" VARCHAR2(80 CHAR), 
	"DISTI_BOOK_COST_EXCHANGE_RATE" VARCHAR2(80 CHAR), 
	"DISTI_BRANCH_CODE" VARCHAR2(80 CHAR), 
	"CLAIM_NUM" VARCHAR2(80 CHAR), 
	"TRACKING_NUM" VARCHAR2(80 CHAR), 
	"END_CUST_NAME" VARCHAR2(80 CHAR), 
	"END_CUST_DISTI_ACCT_NUM" VARCHAR2(80 CHAR), 
	"END_CUST_CITY" VARCHAR2(80 CHAR), 
	"END_CUST_STATE" VARCHAR2(80 CHAR), 
	"END_CUST_ZIP" VARCHAR2(80 CHAR), 
	"END_CUST_COUNTRY" VARCHAR2(80 CHAR), 
	"SEGMENT" VARCHAR2(80 CHAR), 
	"OPP_REG_NUM" VARCHAR2(80 CHAR), 
	"QUOTE_NUM" VARCHAR2(80 CHAR), 
	"QUOTE_ITEM_NUM" VARCHAR2(80 CHAR), 
	"REJECTED_ON" DATE, 
	"REJECTED_BY" VARCHAR2(80 CHAR), 
	"DELETED_ON" DATE, 
	"DELETED_BY" VARCHAR2(80 CHAR), 
	"IMPORT_OID" NUMBER NOT NULL ENABLE, 
	"BUCKET_PART_OID" NUMBER NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(1024 CHAR), 
	"INVOICE_LINE_NUM" VARCHAR2(80 CHAR), 
	"ORIGINAL_INVOICE_LINE_NUM" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_INVOICE_DATE" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_EXPORT_DATE" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_AMOUNT" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_IMPORT_DATE" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_ITEM_NUM" VARCHAR2(80 CHAR), 
	"CREDIT_MEMO_NUM" VARCHAR2(80 CHAR), 
	"CUST_CDM_ID" VARCHAR2(80 CHAR), 
	"END_CUST_CDM_ID" VARCHAR2(80 CHAR), 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "POS_TRACKING_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1" 
  PARALLEL;

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"PRICE_BOOK_TEMPLATE_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"DELTA_REPORT_STATUS" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PRICE_BOOK_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_DELTA_REPORT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR), 
	"OLD_PRICE" NUMBER(38,6), 
	"NEW_PRICE" NUMBER(38,6), 
	"PRICING_REGION_OID" NUMBER NOT NULL ENABLE, 
	"SEGMENT_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"COUNTRY_TYPE_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "PRICE_BOOK_DELTA_REPORT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"MPN" VARCHAR2(80 CHAR), 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_BOOK_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_OID" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,2) NOT NULL ENABLE, 
	"PRICING_REGION_OID" NUMBER NOT NULL ENABLE, 
	"SEGMENT_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"COUNTRY_TYPE_OID" NUMBER NOT NULL ENABLE, 
	"BUSINESS_RULE_OID" NUMBER NOT NULL ENABLE, 
	"LIST_PRICE" NUMBER(38,2) NOT NULL ENABLE, 
	"HISTORICAL_PRICE_BOOK_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "PRICE_BOOK_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_PART_FILTERS" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_TEMPLATE_OID" NUMBER NOT NULL ENABLE, 
	"FILTER_TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"TYPE_OID" NUMBER NOT NULL ENABLE, 
	"TYPE_VALUE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_BOOK_PART_FILTERS_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_TEMPLATE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) DEFAULT 'Active' NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_BOOK_TEMPLATE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRICE_BOOK_TEMPLATE_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_TMPL_COLS" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_TEMPLATE_OID" NUMBER NOT NULL ENABLE, 
	"SELECTED_COLUMN" VARCHAR2(80 CHAR), 
	"COLUMN_LABEL" VARCHAR2(80 CHAR), 
	"LIST_ORDER" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_BOOK_TMPL_COLS_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_TMPL_DIM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"TYPE_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_TEMPLATE_OID" NUMBER NOT NULL ENABLE, 
	"TYPE_LABEL" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PRICE_BOOK_TMPL_DIM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_BOOK_TMPL_HIST" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_BOOK_TEMPLATE_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PRICE_BOOK_TMPL_HIST_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_CATEGORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(20 CHAR), 
	 CONSTRAINT "PRICE_CATEGORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE, 
	"IMPLEMENTATION_DATE" DATE, 
	"PRICE_TABLE_DEFINITION_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_LIST_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_ATTRIB_CRIT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_LIST_RULE_OID" NUMBER NOT NULL ENABLE, 
	"ATTRIB_HEADER_KEY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DATA1" VARCHAR2(165 CHAR), 
	"DATA2" VARCHAR2(165 CHAR), 
	"DATA3" VARCHAR2(165 CHAR), 
	"DATA4" VARCHAR2(165 CHAR), 
	"DATA5" VARCHAR2(165 CHAR), 
	"DATA6" VARCHAR2(165 CHAR), 
	"DATA7" VARCHAR2(165 CHAR), 
	"DATA8" VARCHAR2(165 CHAR), 
	"DATA9" VARCHAR2(165 CHAR), 
	"DATA10" VARCHAR2(165 CHAR), 
	"DATA11" VARCHAR2(165 CHAR), 
	"DATA12" VARCHAR2(165 CHAR), 
	"DATA13" VARCHAR2(165 CHAR), 
	"DATA14" VARCHAR2(165 CHAR), 
	"DATA15" VARCHAR2(165 CHAR), 
	"DATA16" VARCHAR2(165 CHAR), 
	"DATA17" VARCHAR2(165 CHAR), 
	"DATA18" VARCHAR2(165 CHAR), 
	"DATA19" VARCHAR2(165 CHAR), 
	"DATA20" VARCHAR2(165 CHAR), 
	"DATA21" VARCHAR2(165 CHAR), 
	"DATA22" VARCHAR2(165 CHAR), 
	"DATA23" VARCHAR2(165 CHAR), 
	"DATA24" VARCHAR2(165 CHAR), 
	"DATA25" VARCHAR2(165 CHAR), 
	"DATA26" VARCHAR2(165 CHAR), 
	"DATA27" VARCHAR2(165 CHAR), 
	"DATA28" VARCHAR2(165 CHAR), 
	"DATA29" VARCHAR2(165 CHAR), 
	"DATA30" VARCHAR2(165 CHAR), 
	 CONSTRAINT "PRICE_LIST_ATTRIB_CRIT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_CF_CRIT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_LIST_RULE_OID" NUMBER NOT NULL ENABLE, 
	"CUST_FIELD_NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"CRITERIA_NUM" NUMBER NOT NULL ENABLE, 
	"VALUE1" VARCHAR2(80 CHAR), 
	"OPERATOR1" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"VALUE2" VARCHAR2(80 CHAR), 
	"VALUE_FOR_FORMULA" NUMBER(38,6), 
	"DATE1" DATE, 
	"DATE2" DATE, 
	 CONSTRAINT "PRICE_LIST_CF_CRIT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_EXCEPTION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_LIST_RULE_OID" NUMBER NOT NULL ENABLE, 
	"FORMULA" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DATA1" VARCHAR2(165 CHAR), 
	"DATA2" VARCHAR2(165 CHAR), 
	"DATA3" VARCHAR2(165 CHAR), 
	"DATA4" VARCHAR2(165 CHAR), 
	"DATA5" VARCHAR2(165 CHAR), 
	"DATA6" VARCHAR2(165 CHAR), 
	"DATA7" VARCHAR2(165 CHAR), 
	"DATA8" VARCHAR2(165 CHAR), 
	"DATA9" VARCHAR2(165 CHAR), 
	"DATA10" VARCHAR2(165 CHAR), 
	"DATA11" VARCHAR2(165 CHAR), 
	"DATA12" VARCHAR2(165 CHAR), 
	"DATA13" VARCHAR2(165 CHAR), 
	"DATA14" VARCHAR2(165 CHAR), 
	"DATA15" VARCHAR2(165 CHAR), 
	"DATA16" VARCHAR2(165 CHAR), 
	"DATA17" VARCHAR2(165 CHAR), 
	"DATA18" VARCHAR2(165 CHAR), 
	"DATA19" VARCHAR2(165 CHAR), 
	"DATA20" VARCHAR2(165 CHAR), 
	"DATA21" VARCHAR2(165 CHAR), 
	"DATA22" VARCHAR2(165 CHAR), 
	"DATA23" VARCHAR2(165 CHAR), 
	"DATA24" VARCHAR2(165 CHAR), 
	"DATA25" VARCHAR2(165 CHAR), 
	"DATA26" VARCHAR2(165 CHAR), 
	"DATA27" VARCHAR2(165 CHAR), 
	"DATA28" VARCHAR2(165 CHAR), 
	"DATA29" VARCHAR2(165 CHAR), 
	"DATA30" VARCHAR2(165 CHAR), 
	 CONSTRAINT "PRICE_LIST_EXCEPTION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_LIST_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PRICE_LIST_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_LIST_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"BASE_PRICE" NUMBER(36,8), 
	"SORT_ORDER1" NUMBER(36,8) NOT NULL ENABLE, 
	"SORT_ORDER2" NUMBER(36,8) NOT NULL ENABLE, 
	"DATA1" VARCHAR2(80 CHAR), 
	"DATA2" VARCHAR2(80 CHAR), 
	"DATA3" VARCHAR2(80 CHAR), 
	"DATA4" VARCHAR2(80 CHAR), 
	"DATA5" VARCHAR2(80 CHAR), 
	"DATA6" VARCHAR2(80 CHAR), 
	"DATA7" VARCHAR2(80 CHAR), 
	"DATA8" VARCHAR2(80 CHAR), 
	"DATA9" VARCHAR2(80 CHAR), 
	"DATA10" VARCHAR2(80 CHAR), 
	"DATA11" VARCHAR2(80 CHAR), 
	"DATA12" VARCHAR2(80 CHAR), 
	"DATA13" VARCHAR2(80 CHAR), 
	"DATA14" VARCHAR2(80 CHAR), 
	"DATA15" VARCHAR2(80 CHAR), 
	"DATA16" VARCHAR2(80 CHAR), 
	"DATA17" VARCHAR2(80 CHAR), 
	"DATA18" VARCHAR2(80 CHAR), 
	"DATA19" VARCHAR2(80 CHAR), 
	"DATA20" VARCHAR2(80 CHAR), 
	"DATA21" VARCHAR2(80 CHAR), 
	"DATA22" VARCHAR2(80 CHAR), 
	"DATA23" VARCHAR2(80 CHAR), 
	"DATA24" VARCHAR2(80 CHAR), 
	"DATA25" VARCHAR2(80 CHAR), 
	"DATA26" VARCHAR2(80 CHAR), 
	"DATA27" VARCHAR2(80 CHAR), 
	"DATA28" VARCHAR2(80 CHAR), 
	"DATA29" VARCHAR2(80 CHAR), 
	"DATA30" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PRICE_LIST_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_RULE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"PRIORITY" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"FORMULA" VARCHAR2(4000 CHAR), 
	"MULTIPLIER" NUMBER(38,6) NOT NULL ENABLE, 
	"PRICE_COLUMN" VARCHAR2(80 CHAR), 
	"FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "PRICE_LIST_RULE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_RULE_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_LIST_RULE_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(200 CHAR), 
	 CONSTRAINT "PRICE_LIST_RULE_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_LIST_RULE_SUB_FAM_MAP" 
   (	"PRICE_LIST_RULE_OID" NUMBER NOT NULL ENABLE, 
	"SUB_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRC_LST_RL_SB_FM_MP_UK1" UNIQUE ("PRICE_LIST_RULE_OID", "SUB_FAMILY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_PROTECTION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"REVIEW_END_DATE" DATE, 
	"INVENTORY_VALUE" NUMBER(38,6), 
	"TOTAL_CREDIT" NUMBER(38,6), 
	"EFFECTIVE_DATE" DATE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "PRICE_PROTECTION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_PROTECTION_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_PROTECTION_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"OLD_PRICE" NUMBER(38,6), 
	"NEW_PRICE" NUMBER(38,6), 
	"DBC_CREDIT" NUMBER(38,6), 
	"CALCULATED_QOH" NUMBER NOT NULL ENABLE, 
	"ADJUSTED_QOH" NUMBER NOT NULL ENABLE, 
	"ELIGIBLE_QUANTITY" NUMBER NOT NULL ENABLE, 
	"TOTAL_VALUE" NUMBER(38,6) NOT NULL ENABLE, 
	"PRICE_ADJUSTMENT" NUMBER(38,6) NOT NULL ENABLE, 
	"REASON" VARCHAR2(1024 CHAR), 
	"MODIFIED_ADJUSTMENT" NUMBER(38,6), 
	"ALERT_FLAG" NUMBER, 
	"PRICE_POINT_FIELD_OID" NUMBER NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"NEW_PRICE_SOURCE_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_EFFECTIVE_DATE" DATE, 
	"NEW_PRICE_SOURCE" VARCHAR2(3 CHAR), 
	"OLD_PRICE_SOURCE" VARCHAR2(3 CHAR), 
	"OLD_PRICE_SOURCE_OID" NUMBER NOT NULL ENABLE, 
	"REPORTED_QOH" NUMBER NOT NULL ENABLE, 
	"REPORTED_DATE" DATE, 
	"CALCULATED_ELIGIBLE_QUANTITY" NUMBER NOT NULL ENABLE, 
	"FREEZE_ELIGIBLE_QUANTITY" NUMBER NOT NULL ENABLE, 
	"CALCULATED_DBC_CREDIT" NUMBER, 
	"FREEZE_DBC_CREDIT" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "PRICE_PROTECTION_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_PROTECTION_ITEM_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_PROTECTION_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"IS_COMMENT" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "PRC_PRTCTN_TM_HSTRY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_PROTECTION_ITEM_SHIPMENT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_BUCKET_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_PROTECTION_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"PRICE_TYPE" NUMBER NOT NULL ENABLE, 
	"IS_ELIGIBLE" NUMBER NOT NULL ENABLE, 
	"ELIGIBLE_QUANTITY" NUMBER NOT NULL ENABLE, 
	"PRICE_ADJUSTMENT" NUMBER(38,6) NOT NULL ENABLE, 
	"IS_PARTIAL" NUMBER NOT NULL ENABLE, 
	"SHIPMENT_DATE" DATE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"AVAILABLE_DATE" DATE, 
	 CONSTRAINT "PRC_PRTCTN_TM_SHPMNT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_TABLE_DEFINITION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"DEFAULT_DEFINITION" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"STATUS" NUMBER DEFAULT '1' NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_TABLE_DEFINITION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRICE_TABLE_DEFINITION_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_TABLE_DEF_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICE_TABLE_DEFINITION_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(80 CHAR), 
	 CONSTRAINT "PRICE_TABLE_DEF_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_TABLE_DIMENSION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"TYPE_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_TABLE_DEFINITION_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_TABLE_DIMENSION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICE_TABLE_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"MPN" VARCHAR2(80 CHAR), 
	"TEXT" VARCHAR2(1024 CHAR), 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"PRICE_TABLE_DEFINITION_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "PRICE_TABLE_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICING" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY_BREAK_OID" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6), 
	"PRICE_TABLE_DEFINITION_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PRICING_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRICING_UK1" UNIQUE ("PART_OID", "QUANTITY_BREAK_OID", "PRICE_TABLE_DEFINITION_OID", "EFFECTIVE_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICING_DATE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"SHOW_IN_SEARCH" NUMBER NOT NULL ENABLE, 
	"RESTRICT_VIEW_PRICE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRICING_DATE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICING_GROUP_CUSTOMER_MAPPING" 
   (	"PRICING_GROUP_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRCNG_GRP_CSTMR_MPPNG_UK1" UNIQUE ("PRICING_GROUP_CUSTOMER_OID", "CUSTOMER_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICING_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY_BREAK_OID" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6), 
	"EFFECTIVE_DATE" DATE, 
	 CONSTRAINT "PRICING_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRICING_HISTORY_UK1" UNIQUE ("PART_OID", "QUANTITY_BREAK_OID", "EFFECTIVE_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICING_REGION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "PRICING_REGION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRICING_REGION_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRICING_TIMEFRAME" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NUMBER_OF_MONTHS" NUMBER NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(20 CHAR), 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"SHOW_IN_SEARCH" NUMBER NOT NULL ENABLE, 
	"RESTRICT_VIEW_PRICE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRICING_TIMEFRAME_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRODUCT_FAMILY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"LIST_ORDER" NUMBER NOT NULL ENABLE, 
	"FAMILY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80 CHAR), 
	"MARGIN_THRESHOLD" NUMBER(38,6), 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"TYPE" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"PF_CODE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"WIN_THRESHOLD" NUMBER(38,6), 
	"WIN_THRESHOLD_DURATION" NUMBER, 
	 CONSTRAINT "PRODUCT_FAMILY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PROGRAM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PROGRAM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PROGRAM_DIST_MAPPING" 
   (	"PROGRAM_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PROGRAM_DIST_MAPPING_UK1" UNIQUE ("PROGRAM_OID", "DISTRIBUTOR_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."PRO_USER" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"USERID" VARCHAR2(80 CHAR), 
	"PASSWORD" VARCHAR2(256 CHAR), 
	"INIT_PASS" VARCHAR2(80 CHAR), 
	"SALT" VARCHAR2(256 CHAR), 
	"LAST_NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(80 CHAR), 
	"FAX" VARCHAR2(80 CHAR), 
	"EMAIL" VARCHAR2(80 CHAR), 
	"PAGER" VARCHAR2(80 CHAR), 
	"TITLE" VARCHAR2(80 CHAR), 
	"ADDRESS_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"TIME_ZONE" VARCHAR2(30 CHAR), 
	"DATE_FORMAT" VARCHAR2(80 CHAR), 
	"CELL_PHONE" VARCHAR2(80 CHAR), 
	"CLASSIFICATION" VARCHAR2(80 CHAR), 
	"RECORD_ID" NUMBER, 
	"SHOW_TO_MFR" NUMBER NOT NULL ENABLE, 
	"SHOW_TO_DISTI" NUMBER NOT NULL ENABLE, 
	"SHOW_TO_CUST" NUMBER NOT NULL ENABLE, 
	"USER_TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"OWNED_BY_DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"NUMBER_FORMAT" VARCHAR2(80 CHAR), 
	"NUM_FAILED_ATTEMPTS" NUMBER NOT NULL ENABLE, 
	"LAST_LOGIN_DATE" DATE, 
	"LAST_PASSWORD_UPDATE" DATE, 
	"VIEW_ONLY" NUMBER NOT NULL ENABLE, 
	"HAS_DELEGATED" NUMBER NOT NULL ENABLE, 
	"DELEGATED_TO_OID" NUMBER NOT NULL ENABLE, 
	"EFFECTIVE_FROM" DATE, 
	"EFFECTIVE_TO" DATE, 
	"IS_DELEGATE" NUMBER NOT NULL ENABLE, 
	"MINDTOUCH_USERID" VARCHAR2(80 CHAR), 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"DISTI_FLAG" NUMBER NOT NULL ENABLE, 
	"SUPPRESS_WORKFLOW_EMAILS" NUMBER NOT NULL ENABLE, 
	"IS_SSO_USER" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "PRO_USER_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRO_USER_UK1" UNIQUE ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRO_USER_UK2" UNIQUE ("RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "PRO_USER_UK3" UNIQUE ("SFDC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1" 
  PARALLEL;
