CREATE TABLE "HT_REGRESSION_QA"."QUANTITY_BREAK" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"COLUMN_NUM" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(80 CHAR), 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"SHOW_IN_SEARCH" NUMBER NOT NULL ENABLE, 
	"RESTRICT_VIEW_PRICE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUANTITY_BREAK_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"EXPIRATION_DATE" DATE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"END_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"PROGRAM_OID" NUMBER NOT NULL ENABLE, 
	"ASSEMBLY_OID" NUMBER NOT NULL ENABLE, 
	"SALES_CHANNEL" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"ITEMS" NUMBER NOT NULL ENABLE, 
	"BUDGETARY" NUMBER NOT NULL ENABLE, 
	"CLOSURE" NUMBER(38,2) NOT NULL ENABLE, 
	"TOTAL_DOLLARS" NUMBER(38,2) NOT NULL ENABLE, 
	"PO_NUM" VARCHAR2(80 CHAR), 
	"PRO_ORDER_OID" NUMBER NOT NULL ENABLE, 
	"DEBIT_OID" NUMBER NOT NULL ENABLE, 
	"QUOTE_STATUS_OID" NUMBER NOT NULL ENABLE, 
	"PREP_COMPLETE" NUMBER NOT NULL ENABLE, 
	"IS_FORWARD" NUMBER NOT NULL ENABLE, 
	"PARENT_QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"DISTI_COMPANY_ORG_OID" NUMBER NOT NULL ENABLE, 
	"EXPIRATION_DEFAULT" DATE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"DEFAULT_SEGMENT_OID" NUMBER NOT NULL ENABLE, 
	"IS_SEGMENT_OVERRIDE" NUMBER NOT NULL ENABLE, 
	"QUOTE_TYPE_OID" NUMBER NOT NULL ENABLE, 
	"IMPORT_FORMAT_OID" NUMBER NOT NULL ENABLE, 
	"HAS_MULTIPLE_END_CUSTOMERS" NUMBER NOT NULL ENABLE, 
	"HAS_ORDERS" NUMBER NOT NULL ENABLE, 
	"CONTRACT_TYPE" VARCHAR2(80 CHAR), 
	"CONTRACT_DEFAULT_EC_VALUE" VARCHAR2(80 CHAR), 
	"CONTRACT_CUST_IS_BY_CORP_ID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_EC_IS_BY_CORP_ID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_IS_COST" NUMBER NOT NULL ENABLE, 
	"CONTRACT_IS_SHIP" NUMBER NOT NULL ENABLE, 
	"CONTRACT_CPN_REQUIRED" NUMBER NOT NULL ENABLE, 
	"CONTRACT_LIMIT" NUMBER NOT NULL ENABLE, 
	"CONTRACT_PROG_ASSEM_REQUIRED" NUMBER NOT NULL ENABLE, 
	"IS_CONTRACT" NUMBER NOT NULL ENABLE, 
	"QUOTE_NUM" VARCHAR2(80 CHAR), 
	"CEM_FLAG" NUMBER NOT NULL ENABLE, 
	"DISTI_FLAG" NUMBER NOT NULL ENABLE, 
	"PRICING_GROUP_TYPE" VARCHAR2(80 CHAR), 
	"CURRENCY_RULE" NUMBER NOT NULL ENABLE, 
	"CURRENCY_RULE_DATE" DATE, 
	"COMPLIANCE" NUMBER(38,2) NOT NULL ENABLE, 
	"PARENT_DESIGN_REG_OID" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"WORKFLOW_STEP" VARCHAR2(80 CHAR), 
	"CAN_BE_ORDERED" NUMBER NOT NULL ENABLE, 
	"BILL_CONTACT_OID" NUMBER NOT NULL ENABLE, 
	"SHIP_CONTACT_OID" NUMBER NOT NULL ENABLE, 
	"BILL_TO_ADDRESS_OID" NUMBER NOT NULL ENABLE, 
	"SHIP_TO_ADDRESS_OID" NUMBER NOT NULL ENABLE, 
	"SHIPMENT_METHOD_OID" NUMBER NOT NULL ENABLE, 
	"BROKER_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"DEFAULT_MATRIX_INFO_OID" NUMBER NOT NULL ENABLE, 
	"MATRIX_TOP_LEFT" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_OID" NUMBER NOT NULL ENABLE, 
	"MIGRATED_CONTRACT" NUMBER NOT NULL ENABLE, 
	"OPEN_DATE" DATE, 
	"QUOTE_ANY_CURRENCY" NUMBER NOT NULL ENABLE, 
	"DEFAULT_MATRIX_TYPE" VARCHAR2(20 CHAR), 
	"CONTRACT_LEVEL_OID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_COST_RESALE" VARCHAR2(10 CHAR), 
	"CONTRACT_PRICE_IS" VARCHAR2(10 CHAR), 
	"IS_MATRIX" NUMBER NOT NULL ENABLE, 
	"INCLUDE_EXCLUDE_TYPE" NUMBER NOT NULL ENABLE, 
	"VERSION_NUM" NUMBER NOT NULL ENABLE, 
	"CONTRACT_STATUS" VARCHAR2(80 CHAR), 
	"PARENT_CONTRACT_OID" NUMBER NOT NULL ENABLE, 
	"CURRENCY_RULE_DATE_TYPE" NUMBER NOT NULL ENABLE, 
	"IS_DEBIT_MATRIX" NUMBER NOT NULL ENABLE, 
	"TERMS_AND_CONDITIONS" VARCHAR2(4000 CHAR), 
	"IS_BLANKET" NUMBER NOT NULL ENABLE, 
	"DEBIT_START_DATE" DATE, 
	"IS_UNLIMITED_QUANTITY" NUMBER NOT NULL ENABLE, 
	"DEAL_SCORE" NUMBER NOT NULL ENABLE, 
	"DEBIT_EXPIRATION_DATE" DATE, 
	"START_DATE" DATE, 
	"VOIDED_DATE" DATE, 
	"APPROVED_DATE" DATE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "QUOTE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_CEM_MAPPING" 
   (	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_CEM_MAPPING_UK1" UNIQUE ("QUOTE_OID", "CUSTOMER_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_CONTRACT_ITEM_MAPPING" 
   (	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"IS_MIGRATED" NUMBER DEFAULT '1' NOT NULL ENABLE, 
	 CONSTRAINT "QT_CNTRCT_TM_MPPNG_UK1" UNIQUE ("QUOTE_ITEM_OID", "CONTRACT_ITEM_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_CONTRACT_MAPPING" 
   (	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_OID" NUMBER NOT NULL ENABLE, 
	"IS_MIGRATED" NUMBER DEFAULT '1' NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_CONTRACT_MAPPING_UK1" UNIQUE ("QUOTE_OID", "CONTRACT_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_CORP_ID_MAPPING" 
   (	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"CORPORATE_ID_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_CORP_ID_MAPPING_UK1" UNIQUE ("QUOTE_OID", "CORPORATE_ID_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_CURRENCY_RATE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_CURRENCY_RATE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "QUOTE_CURRENCY_RATE_UK1" UNIQUE ("QUOTE_OID", "CURRENCY_INFO_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_CUSTOMER_MAPPING" 
   (	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_CUSTOMER_MAPPING_UK1" UNIQUE ("QUOTE_OID", "CUSTOMER_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_DIST_MAPPING" 
   (	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_DIST_MAPPING_UK1" UNIQUE ("QUOTE_OID", "DISTRIBUTOR_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_DURATION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"MONTH" NUMBER NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(80 CHAR), 
	"DEFAULT_SELECTED" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_DURATION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ERROR_MAPPING" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_ERROR_MAPPING_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"MPN" VARCHAR2(80 CHAR), 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"PRICE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(80 CHAR), 
	"END_CUSTOMER_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"ITEM_NUM" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY_REQUESTED" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"ESTIMATED_ANNUAL_USAGE" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"MONTHS" NUMBER NOT NULL ENABLE, 
	"OEM_PRICE" NUMBER(38,6), 
	"DISTI_COST" NUMBER(38,6), 
	"DISTI_RESALE" NUMBER(38,6), 
	"ADDERS_COST" NUMBER(38,6), 
	"TARGET_PRICE" NUMBER(38,6), 
	"COMPETITOR_OID" NUMBER NOT NULL ENABLE, 
	"COMP_PART_OID" NUMBER NOT NULL ENABLE, 
	"QUOTE_JUSTIFICATION" VARCHAR2(512 CHAR), 
	"REQUOTE_PRICE" NUMBER(38,6), 
	"ADJ_DISTI_COST" NUMBER(38,6), 
	"ADJ_DISTI_RESALE" NUMBER(38,6), 
	"MARKETING_COMMENT" VARCHAR2(1024 CHAR), 
	"ORDER_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"HAS_ORDER_ITEMS" NUMBER NOT NULL ENABLE, 
	"DEBIT_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"DESIGN_PART_MAPPING_OID" NUMBER NOT NULL ENABLE, 
	"DISPLAY_DATA" VARCHAR2(20 CHAR), 
	"REF_PRICE" NUMBER(38,6), 
	"MINIMUM_PRICE" NUMBER(38,6), 
	"FIELD_MIN" NUMBER(38,6), 
	"DISTI_BOOK_COST" NUMBER(38,6), 
	"MANUFACTURER_COST" NUMBER(38,6), 
	"ALERT_FLAG" NUMBER NOT NULL ENABLE, 
	"CALL_MARKETING" NUMBER NOT NULL ENABLE, 
	"MPP_OID" NUMBER NOT NULL ENABLE, 
	"EXPIRATION_DATE" DATE, 
	"CUST_PART_MAPPING_OID" NUMBER NOT NULL ENABLE, 
	"RECOMMENDED_PRICE" NUMBER(38,6), 
	"RECOMMENDED_PRICE_COMMENT" VARCHAR2(80 CHAR), 
	"CONTRACT_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"DEBIT_EXPIRATION_DATE" DATE, 
	"MPP_PRICE" NUMBER(38,6), 
	"COMMISSION_RATE" NUMBER(38,6), 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"SEGMENT_OID" NUMBER NOT NULL ENABLE, 
	"IS_SEGMENT_OVERRIDE" NUMBER NOT NULL ENABLE, 
	"REQUOTE_DATE" DATE, 
	"DBC_EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"IS_AUTOMATED" NUMBER NOT NULL ENABLE, 
	"PRICING_DESIGN_REG_OID" NUMBER NOT NULL ENABLE, 
	"PART_EXT" VARCHAR2(80 CHAR), 
	"WIN_DATE" DATE, 
	"LOSS_DATE" DATE, 
	"BUSINESS_RULE_OID" NUMBER NOT NULL ENABLE, 
	"PRICING_CONVERSION_OID" NUMBER NOT NULL ENABLE, 
	"IS_STEP_CONTRACT" NUMBER NOT NULL ENABLE, 
	"QUANTITY_COMPLIANCE" NUMBER NOT NULL ENABLE, 
	"END_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"PROGRAM_OID" NUMBER NOT NULL ENABLE, 
	"ASSEMBLY_OID" NUMBER NOT NULL ENABLE, 
	"AUTO_REQUOTE_PRICE" NUMBER(38,6), 
	"AUTO_ADJ_DISTI_COST" NUMBER(38,6), 
	"AUTO_ADJ_DISTI_RESALE" NUMBER(38,6), 
	"IS_NO_BID" NUMBER NOT NULL ENABLE, 
	"NO_BID_COMMENT" VARCHAR2(1024 CHAR), 
	"CONTRACT_EC_IS_BY_CORP_ID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_IS_STEP_CONTRACT" NUMBER NOT NULL ENABLE, 
	"CEM_FLAG" NUMBER NOT NULL ENABLE, 
	"DISTI_FLAG" NUMBER NOT NULL ENABLE, 
	"TYPE1_PRICING_CONVERSION_OID" NUMBER NOT NULL ENABLE, 
	"OEM_PRICE_DEF_OID" NUMBER NOT NULL ENABLE, 
	"DBC_PRICE_DEF_OID" NUMBER NOT NULL ENABLE, 
	"IS_SPECIAL_BUY" NUMBER NOT NULL ENABLE, 
	"IS_STOCK_ROTATION" NUMBER NOT NULL ENABLE, 
	"IS_PRICE_PROTECTION" NUMBER NOT NULL ENABLE, 
	"MATRIX_INFO_OID" NUMBER NOT NULL ENABLE, 
	"MATRIX_TARGETS_OID" NUMBER NOT NULL ENABLE, 
	"MATRIX_PERCENTS_OID" NUMBER NOT NULL ENABLE, 
	"MATRIX_TARGET_PERIOD" NUMBER, 
	"MATRIX_TARGET_QUANTITY" NUMBER, 
	"MATRIX_SOP" DATE, 
	"WORKFLOW_STATUS" VARCHAR2(80 CHAR), 
	"TRANSACTION_GROUP_ID" NUMBER NOT NULL ENABLE, 
	"MATRIX_REC_PRICES_OID" NUMBER NOT NULL ENABLE, 
	"MATRIX_FORECASTS_OID" NUMBER NOT NULL ENABLE, 
	"MATRIX_STARTING_PRICE" NUMBER(38,6), 
	"MATRIX_STARTING_COST" NUMBER(38,6), 
	"MATRIX_STARTING_RESALE" NUMBER(38,6), 
	"MATRIX_LOWEST_PRICE_ALLOWED" NUMBER(38,6), 
	"MATRIX_FLOOR_REACHED" NUMBER NOT NULL ENABLE, 
	"RECOMMENDED_COST" NUMBER(38,6), 
	"RECOMMENDED_COST_COMMENT" VARCHAR2(80 CHAR), 
	"IS_BUDGETARY" NUMBER NOT NULL ENABLE, 
	"PRICE_ACTION" VARCHAR2(80 CHAR), 
	"MATRIX_TARGET_COSTS_OID" NUMBER NOT NULL ENABLE, 
	"INITIAL_SUBMITTED_DATE" DATE, 
	"LAST_APPROVED_DATE" DATE, 
	"MATRIX_REC_COSTS_OID" NUMBER NOT NULL ENABLE, 
	"QUOTE_TYPE_OID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_CPN_REQUIRED" NUMBER NOT NULL ENABLE, 
	"CONTRACT_EC_VALUE" VARCHAR2(10 CHAR), 
	"CONTRACT_MIN_PER_ORDER" NUMBER NOT NULL ENABLE, 
	"CONTRACT_MULT_PER_ORDER" NUMBER NOT NULL ENABLE, 
	"CONTRACT_IS_SHIP" NUMBER NOT NULL ENABLE, 
	"RECOMMENDED_RESALE" NUMBER(38,6), 
	"RECOMMENDED_RESALE_COMMENT" VARCHAR2(80 CHAR), 
	"MATRIX_USAGE_PRIOR_SOP" NUMBER NOT NULL ENABLE, 
	"ACCUMULATED_USAGE" NUMBER NOT NULL ENABLE, 
	"MATRIX_PERIOD_USAGES_OID" NUMBER NOT NULL ENABLE, 
	"MATRIX_ACTIVE_PRICE" NUMBER(38,6), 
	"MATRIX_ACTIVE_RESALE" NUMBER(38,6), 
	"MATRIX_ACTIVE_COST" NUMBER(38,6), 
	"REPRICE_BACKLOG" NUMBER NOT NULL ENABLE, 
	"MATRIX_REC_RESALES_OID" NUMBER NOT NULL ENABLE, 
	"SUB_ITEM_NUM" NUMBER NOT NULL ENABLE, 
	"PART_TYPE" NUMBER NOT NULL ENABLE, 
	"PARENT_KIT_OID" NUMBER NOT NULL ENABLE, 
	"KIT_COMPONENT_OID" NUMBER NOT NULL ENABLE, 
	"KIT_COMPONENT_QTY" NUMBER NOT NULL ENABLE, 
	"ALACARTE_PRICE" NUMBER(38,6), 
	"ALACARTE_DISTI_COST" NUMBER(38,6), 
	"ALACARTE_DISTI_RESALE" NUMBER(38,6), 
	"ALACARTE_ADJ_PRICE" NUMBER(38,6), 
	"ALACARTE_ADJ_DISTI_COST" NUMBER(38,6), 
	"ALACARTE_ADJ_DISTI_RESALE" NUMBER(38,6), 
	"IS_DEBIT_MATRIX_ITEM" NUMBER NOT NULL ENABLE, 
	"CREATED_FROM_OPP_ITEM_SFDC_ID" VARCHAR2(80 CHAR), 
	"DEBIT_START_DATE" DATE, 
	"THRESHOLD_PRICE" NUMBER(38,6), 
	"REBATE_AMT" NUMBER(38,6), 
	"DISTI_REBATE_AMT" NUMBER(38,6), 
	"POCKET_PRICE" NUMBER(38,6), 
	"POCKET_COST_PRICE" NUMBER(38,6), 
	"RECOMMENDED_POCKET_PRICE" NUMBER(38,6), 
	"RECOMMENDED_POCKET_COST" NUMBER(38,6), 
	"DISTI_POCKET_PRICE" NUMBER(38,6), 
	"THRESHOLD_OVERRIDE" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_VERSION" NUMBER NOT NULL ENABLE, 
	"IS_UNLIMITED_QUANTITY" NUMBER NOT NULL ENABLE, 
	"DEAL_SCORE" NUMBER NOT NULL ENABLE, 
	"IS_MATRIX" NUMBER NOT NULL ENABLE, 
	"MATRIX_REC_PERCENTS_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY_RECOMMENDED" NUMBER NOT NULL ENABLE, 
	"DEAL_AUTH_PRICE" NUMBER(38,6), 
	"DEAL_AUTH_QUANTITY" NUMBER, 
	"DEAL_AUTH_EXPIRATION" DATE, 
	"DEAL_AUTH_BUSINESS_RULE_OID" NUMBER NOT NULL ENABLE, 
	"AVAILABLE_QUANTITY" NUMBER NOT NULL ENABLE, 
	"MATRIX_MFR_COSTS_OID" NUMBER NOT NULL ENABLE, 
	"BUNDLE_REBATE_AMT" NUMBER(38,6), 
	"BUNDLE_POCKET_PRICE" NUMBER(38,6), 
	"BUNDLE_POCKET_COST_PRICE" NUMBER(38,6), 
	"DISTI_BUNDLE_REBATE_AMT" NUMBER(38,6), 
	"DISTI_BUNDLE_NET_COST" NUMBER(38,6), 
	"RECOMM_BUNDLE_REBATE_AMT" NUMBER(38,6), 
	"RECOMM_BUNDLE_POCKET_PRICE" NUMBER(38,6), 
	"RECOMM_BUNDLE_POCKET_COST" NUMBER(38,6), 
	"DISTI_REC_BUNDLE_REBATE_AMT" NUMBER(38,6), 
	"DISTI_REC_BUNDLE_NET_COST" NUMBER(38,6), 
	"CONTRACT_LIMIT" NUMBER NOT NULL ENABLE, 
	"DATE_REPRICED" DATE, 
	"REPRICED_BY_OID" NUMBER NOT NULL ENABLE, 
	"CURRENT_PRICE" NUMBER(38,6), 
	"CURRENT_COST" NUMBER(38,6), 
	"CURRENT_RESALE" NUMBER(38,6), 
	"CURRENT_BUSINESS_RULE_OID" NUMBER NOT NULL ENABLE, 
	"CURRENT_CONVERSION_RULE_OID" NUMBER NOT NULL ENABLE, 
	"CURRENT_DEAL_AUTH_PRICE" NUMBER(38,6), 
	"CURRENT_DEAL_AUTH_QUANTITY" NUMBER, 
	"CURRENT_DEAL_AUTH_EXP_DATE" DATE, 
	"CURRENT_DEAL_AUTH_BUS_RULE_OID" NUMBER NOT NULL ENABLE, 
	"BASE_PRICE" NUMBER(38,6), 
	"BASE_COST" NUMBER(38,6), 
	"BASE_RESALE" NUMBER(38,6), 
	"BASE_QUANTITY" NUMBER, 
	"BASE_BUSINESS_RULE_OID" NUMBER NOT NULL ENABLE, 
	"BASE_CONVERSION_RULE_OID" NUMBER NOT NULL ENABLE, 
	"BASE_DEAL_AUTH_PRICE" NUMBER(38,6), 
	"BASE_DEAL_AUTH_QUANTITY" NUMBER, 
	"BASE_DEAL_AUTH_EXP_DATE" DATE, 
	"BASE_DEAL_AUTH_BUS_RULE_OID" NUMBER NOT NULL ENABLE, 
	"BASE_EXPIRATION_DATE" DATE, 
	"CURRENT_SEED_PRICE" NUMBER(38,6), 
	"CURRENT_SEED_COST" NUMBER(38,6), 
	"CURRENT_SEED_RESALE" NUMBER(38,6), 
	"RECOMMENDED_REBATE_AMT" NUMBER(38,6), 
	"ROUTE_TRACKING_STATUS" VARCHAR2(80 CHAR), 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "QUOTE_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_ADDER_MAPPING" 
   (	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"ADDER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_ITEM_ADDER_MAPPING_UK1" UNIQUE ("QUOTE_ITEM_OID", "ADDER_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_BENEFIT_MAPPING" 
   (	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"REBATE_ITEM_BENEFIT_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_ITEM_BENEFIT_MAPPING_UK1" UNIQUE ("QUOTE_ITEM_OID", "REBATE_ITEM_BENEFIT_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_CEM_MAPPING" 
   (	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_ITEM_CEM_MAPPING_UK1" UNIQUE ("QUOTE_ITEM_OID", "CUSTOMER_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_COMMENT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"THE_COMMENT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(80 CHAR) DEFAULT 'Internal' NOT NULL ENABLE, 
	"QUOTE_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_ITEM_COMMENT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_CORP_ID_MAPPING" 
   (	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"CORPORATE_ID_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_ITEM_CORP_ID_MAPPING_UK1" UNIQUE ("QUOTE_ITEM_OID", "CORPORATE_ID_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_DIST_MAPPING" 
   (	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_ITEM_DIST_MAPPING_UK1" UNIQUE ("QUOTE_ITEM_OID", "DISTRIBUTOR_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_PRICE_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"NEW_PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"PRICE_TYPE" VARCHAR2(80 CHAR), 
	"TEXT" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "QUOTE_ITEM_PRICE_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_ITEM_SPLIT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"SPLIT_PERCENT" NUMBER(38,6) NOT NULL ENABLE, 
	"ORG_OID" NUMBER NOT NULL ENABLE, 
	"REP_RATE_PERCENT" NUMBER(38,6), 
	 CONSTRAINT "QUOTE_ITEM_SPLIT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_JUSTIFICATION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"JUSTIFICATION_ORDER" NUMBER NOT NULL ENABLE, 
	"JUSTIFICATION" VARCHAR2(80 CHAR), 
	"REQUIRES_COMP" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_JUSTIFICATION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_MATRIX_DATA" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DATA1" VARCHAR2(80 CHAR), 
	"DATA2" VARCHAR2(80 CHAR), 
	"DATA3" VARCHAR2(80 CHAR), 
	"DATA4" VARCHAR2(80 CHAR), 
	"DATA5" VARCHAR2(80 CHAR), 
	"DATA6" VARCHAR2(80 CHAR), 
	"DATA7" VARCHAR2(80 CHAR), 
	"DATA8" VARCHAR2(80 CHAR), 
	"DATA9" VARCHAR2(80 CHAR), 
	"DATA10" VARCHAR2(80 CHAR), 
	"DATA11" VARCHAR2(80 CHAR), 
	"DATA12" VARCHAR2(80 CHAR), 
	"DATA13" VARCHAR2(80 CHAR), 
	"DATA14" VARCHAR2(80 CHAR), 
	"DATA15" VARCHAR2(80 CHAR), 
	"DATA16" VARCHAR2(80 CHAR), 
	"DATA17" VARCHAR2(80 CHAR), 
	"DATA18" VARCHAR2(80 CHAR), 
	"DATA19" VARCHAR2(80 CHAR), 
	"DATA20" VARCHAR2(80 CHAR), 
	"DATA21" VARCHAR2(80 CHAR), 
	"DATA22" VARCHAR2(80 CHAR), 
	"DATA23" VARCHAR2(80 CHAR), 
	"DATA24" VARCHAR2(80 CHAR), 
	"DATA25" VARCHAR2(80 CHAR), 
	"DATA26" VARCHAR2(80 CHAR), 
	"DATA27" VARCHAR2(80 CHAR), 
	"DATA28" VARCHAR2(80 CHAR), 
	"DATA29" VARCHAR2(80 CHAR), 
	"DATA30" VARCHAR2(80 CHAR), 
	"DATA31" VARCHAR2(80 CHAR), 
	"DATA32" VARCHAR2(80 CHAR), 
	"DATA33" VARCHAR2(80 CHAR), 
	"DATA34" VARCHAR2(80 CHAR), 
	"DATA35" VARCHAR2(80 CHAR), 
	"DATA36" VARCHAR2(80 CHAR), 
	"DATA37" VARCHAR2(80 CHAR), 
	"DATA38" VARCHAR2(80 CHAR), 
	"DATA39" VARCHAR2(80 CHAR), 
	"DATA40" VARCHAR2(80 CHAR), 
	"DATA41" VARCHAR2(80 CHAR), 
	"DATA42" VARCHAR2(80 CHAR), 
	"DATA43" VARCHAR2(80 CHAR), 
	"DATA44" VARCHAR2(80 CHAR), 
	"DATA45" VARCHAR2(80 CHAR), 
	"DATA46" VARCHAR2(80 CHAR), 
	"DATA47" VARCHAR2(80 CHAR), 
	"DATA48" VARCHAR2(80 CHAR), 
	"DATA49" VARCHAR2(80 CHAR), 
	"DATA50" VARCHAR2(80 CHAR), 
	"DATA51" VARCHAR2(80 CHAR), 
	"DATA52" VARCHAR2(80 CHAR), 
	"DATA53" VARCHAR2(80 CHAR), 
	"DATA54" VARCHAR2(80 CHAR), 
	"DATA55" VARCHAR2(80 CHAR), 
	"DATA56" VARCHAR2(80 CHAR), 
	"DATA57" VARCHAR2(80 CHAR), 
	"DATA58" VARCHAR2(80 CHAR), 
	"DATA59" VARCHAR2(80 CHAR), 
	"DATA60" VARCHAR2(80 CHAR), 
	 CONSTRAINT "QUOTE_MATRIX_DATA_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_MATRIX_INFO" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NUM_PERIODS" NUMBER NOT NULL ENABLE, 
	"PERIOD_TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"ALLOW_PARTIAL_PERIOD" NUMBER NOT NULL ENABLE, 
	"DEFAULT_PERIOD_PERCENT" NUMBER(38,6), 
	"DEFAULT_BUCKET_PERCENT" NUMBER(38,6), 
	"PERIOD_START_DATE" DATE, 
	"PERIOD_START_DATES_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY1" VARCHAR2(80 CHAR), 
	"QUANTITY2" VARCHAR2(80 CHAR), 
	"QUANTITY3" VARCHAR2(80 CHAR), 
	"QUANTITY4" VARCHAR2(80 CHAR), 
	"QUANTITY5" VARCHAR2(80 CHAR), 
	"QUANTITY6" VARCHAR2(80 CHAR), 
	"QUANTITY7" VARCHAR2(80 CHAR), 
	"QUANTITY8" VARCHAR2(80 CHAR), 
	"QUANTITY9" VARCHAR2(80 CHAR), 
	"QUANTITY10" VARCHAR2(80 CHAR), 
	 CONSTRAINT "QUOTE_MATRIX_INFO_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_MATRIX_OVERRIDE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"ROW_NUM" NUMBER NOT NULL ENABLE, 
	"COL" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"PRICE_TYPE" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_MATRIX_OVERRIDE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_PARENT_ITEM_MAPPING" 
   (	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"PARENT_ITEM_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_PARENT_ITEM_MAPPING_UK1" UNIQUE ("QUOTE_ITEM_OID", "PARENT_ITEM_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_PF_ALERT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"ALERT_FLAG" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_PF_ALERT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "QUOTE_PF_ALERT_UK1" UNIQUE ("QUOTE_OID", "PRODUCT_FAMILY_OID", "ALERT_FLAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_PRICE_LOG" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"QUOTED_DATE" DATE, 
	"PRICING_OID" NUMBER NOT NULL ENABLE, 
	"PRICING_QUANTITY" NUMBER NOT NULL ENABLE, 
	"IS_ACCOUNTED" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"IS_CLOSED" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_PRICE_LOG_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "QUOTE_PRICE_LOG_UK1" UNIQUE ("QUOTE_ITEM_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_PRINT_TEMPLATE_MAPPING" 
   (	"QUOTE_OID" NUMBER NOT NULL ENABLE, 
	"PRINT_TEMPLATE_ID" NUMBER NOT NULL ENABLE, 
	"PRINT_TEMPLATE_VER_NUM" NUMBER NOT NULL ENABLE, 
	"PRINT_TEMPLATE_TYPE" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"TC_TYPE" NUMBER NOT NULL ENABLE, 
	"ORDER_INDEX" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_SCHEDULE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"SCHED_DATE" DATE, 
	"SCHEDULE_STATUS" NUMBER NOT NULL ENABLE, 
	"RELEASE_NUM" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_SCHEDULE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_STEP_PRICE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"STEP_NUM" NUMBER NOT NULL ENABLE, 
	"REQUESTED_DATE" DATE NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6), 
	"QUANTITY" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"RESALE_PRICE" NUMBER(38,6), 
	"COST_PRICE" NUMBER(38,6), 
	 CONSTRAINT "QUOTE_STEP_PRICE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."QUOTE_TYPE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"TYPE_KEY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"BUDGETARY" NUMBER NOT NULL ENABLE, 
	"IS_FORWARD" NUMBER NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER NOT NULL ENABLE, 
	"IS_DEFAULT" NUMBER NOT NULL ENABLE, 
	"ALLOW_ROOT_PART" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"IS_CONTRACT" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"DIRECT_WORKFLOW" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"DISTI_WORKFLOW" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"SREP_WORKFLOW" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"IS_MATRIX" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "QUOTE_TYPE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "QUOTE_TYPE_UK1" UNIQUE ("TYPE_KEY", "IS_ACTIVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR), 
	"SFDC_REBATE_NUM" VARCHAR2(80 CHAR), 
	"START_DATE" DATE, 
	"EXPIRE_DATE" DATE, 
	"PAYMENT_PERIOD" VARCHAR2(40 CHAR), 
	"STATUS" VARCHAR2(40 CHAR), 
	"TYPE" VARCHAR2(40 CHAR), 
	"SUB_TYPE" VARCHAR2(40 CHAR), 
	"APPLY_TO_NEW" NUMBER NOT NULL ENABLE, 
	"PAY_TO_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"PAY_TO_DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"REBATE_SOURCE" VARCHAR2(20 CHAR), 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_OID" NUMBER NOT NULL ENABLE, 
	"EARNING_FREQUENCY" VARCHAR2(40 CHAR), 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"TOTAL_EARNED_AMT" NUMBER(38,6) NOT NULL ENABLE, 
	"TOTAL_OVERRIDDEN_AMT" NUMBER(38,6) NOT NULL ENABLE, 
	"TOTAL_PROJECTED_AMT" NUMBER(38,6) NOT NULL ENABLE, 
	"TOTAL_PAID_AMT" NUMBER(38,6) NOT NULL ENABLE, 
	"ORIGINAL_REBATE_OID" NUMBER NOT NULL ENABLE, 
	"RECORD_TYPE" VARCHAR2(80 CHAR), 
	"AMENDED_REBATE_OID" NUMBER NOT NULL ENABLE, 
	"SUBSEQUENT_REBATE_OID" NUMBER NOT NULL ENABLE, 
	"REVISION_NUMBER" NUMBER NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "REBATE_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE_ENROLLMENT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"REBATE_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	 CONSTRAINT "REBATE_ENROLLMENT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE_FILTER" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"FILTER_TYPE" VARCHAR2(100 CHAR), 
	"FILTER_VALUE" VARCHAR2(100 CHAR), 
	"INCLUDE_EXCLUDE_TYPE" NUMBER NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"FILTER_EXPRESSION_ID" VARCHAR2(80 CHAR), 
	"REBATE_ITEM_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"REBATE_ITEM_BENEFIT_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"REBATE_ITEM_QUALIFICATION_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"IS_BUNDLE" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"ADDITIONAL_ATTRIB1_NAME" VARCHAR2(80 CHAR), 
	"ADDITIONAL_ATTRIB1_VALUE" VARCHAR2(80 CHAR), 
	 CONSTRAINT "REBATE_FILTER_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"REBATE_OID" NUMBER NOT NULL ENABLE, 
	"REBATE_ITEM_BENEFIT_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "REBATE_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"REBATE_OID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR), 
	"DATA_SOURCE" VARCHAR2(80 CHAR), 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"QUALIFICATION_METHOD" VARCHAR2(80 CHAR), 
	"ENROLLED_ACCOUNT_TYPE" VARCHAR2(80 CHAR), 
	"ADV_FILTER_EXPR" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "REBATE_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE_ITEM_BENEFIT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"REBATE_OID" NUMBER NOT NULL ENABLE, 
	"REBATE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"BENEFIT_NAME" VARCHAR2(200 CHAR), 
	"BENEFIT_TYPE" VARCHAR2(80 CHAR), 
	"STATUS" VARCHAR2(20 CHAR), 
	"NOMINAL_VALUE" NUMBER(38,6), 
	"QUOTE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_GROUP_ID" NUMBER NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"WORKFLOW_VERSION" NUMBER NOT NULL ENABLE, 
	"BENEFIT_COMP_TYPE" NUMBER NOT NULL ENABLE, 
	"ITEM_NUM" NUMBER NOT NULL ENABLE, 
	"SUB_ITEM_NUM" NUMBER NOT NULL ENABLE, 
	"BUNDLE_COMP_QTY" NUMBER NOT NULL ENABLE, 
	"REBATE_ITEM_QUALIFICATION_OID" NUMBER NOT NULL ENABLE, 
	"TIER1_NAME" VARCHAR2(100 CHAR), 
	"TIER1_VALUE" VARCHAR2(100 CHAR), 
	"TIER2_NAME" VARCHAR2(100 CHAR), 
	"TIER2_VALUE" VARCHAR2(100 CHAR), 
	"TIER3_NAME" VARCHAR2(100 CHAR), 
	"TIER3_VALUE" VARCHAR2(100 CHAR), 
	"TIER4_NAME" VARCHAR2(100 CHAR), 
	"TIER4_VALUE" VARCHAR2(100 CHAR), 
	"TIER5_NAME" VARCHAR2(100 CHAR), 
	"TIER5_VALUE" VARCHAR2(100 CHAR), 
	"TIER6_NAME" VARCHAR2(100 CHAR), 
	"TIER6_VALUE" VARCHAR2(100 CHAR), 
	"TIER7_NAME" VARCHAR2(100 CHAR), 
	"TIER7_VALUE" VARCHAR2(100 CHAR), 
	"TIER8_NAME" VARCHAR2(100 CHAR), 
	"TIER8_VALUE" VARCHAR2(100 CHAR), 
	"TIER9_NAME" VARCHAR2(100 CHAR), 
	"TIER9_VALUE" VARCHAR2(100 CHAR), 
	"TIER10_NAME" VARCHAR2(100 CHAR), 
	"TIER10_VALUE" VARCHAR2(100 CHAR), 
	"ORIGINAL_BENEFIT_OID" NUMBER NOT NULL ENABLE, 
	"IS_BULK_BENEFIT" NUMBER NOT NULL ENABLE, 
	"ADV_FILTER_EXPR" VARCHAR2(4000 CHAR), 
	"ROUTE_TRACKING_STATUS" VARCHAR2(80 CHAR), 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "REBATE_ITEM_BENEFIT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "REBATE_ITEM_BENEFIT_UK1" UNIQUE ("REBATE_OID", "REBATE_ITEM_OID", "ITEM_NUM", "SUB_ITEM_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE_ITEM_COMMENT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"REBATE_ITEM_BENEFIT_OID" NUMBER NOT NULL ENABLE, 
	"THE_COMMENT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"REBATE_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "REBATE_ITEM_COMMENT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."REBATE_ITEM_QUALIFICATION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"REBATE_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(255 CHAR), 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"TIER1_NAME" VARCHAR2(100 CHAR), 
	"TIER1_LOW_VALUE" NUMBER(14,4), 
	"TIER1_HIGH_VALUE" NUMBER(14,4), 
	"TIER2_NAME" VARCHAR2(100 CHAR), 
	"TIER2_LOW_VALUE" NUMBER(14,4), 
	"TIER2_HIGH_VALUE" NUMBER(14,4), 
	"TIER3_NAME" VARCHAR2(100 CHAR), 
	"TIER3_LOW_VALUE" NUMBER(14,4), 
	"TIER3_HIGH_VALUE" NUMBER(14,4), 
	"TIER4_NAME" VARCHAR2(100 CHAR), 
	"TIER4_LOW_VALUE" NUMBER(14,4), 
	"TIER4_HIGH_VALUE" NUMBER(14,4), 
	"TIER5_NAME" VARCHAR2(100 CHAR), 
	"TIER5_LOW_VALUE" NUMBER(14,4), 
	"TIER5_HIGH_VALUE" NUMBER(14,4), 
	"TIER6_NAME" VARCHAR2(100 CHAR), 
	"TIER6_LOW_VALUE" NUMBER(14,4), 
	"TIER6_HIGH_VALUE" NUMBER(14,4), 
	"TIER7_NAME" VARCHAR2(100 CHAR), 
	"TIER7_LOW_VALUE" NUMBER(14,4), 
	"TIER7_HIGH_VALUE" NUMBER(14,4), 
	"TIER8_NAME" VARCHAR2(100 CHAR), 
	"TIER8_LOW_VALUE" NUMBER(14,4), 
	"TIER8_HIGH_VALUE" NUMBER(14,4), 
	"TIER9_NAME" VARCHAR2(100 CHAR), 
	"TIER9_LOW_VALUE" NUMBER(14,4), 
	"TIER9_HIGH_VALUE" NUMBER(14,4), 
	"TIER10_NAME" VARCHAR2(100 CHAR), 
	"TIER10_LOW_VALUE" NUMBER(14,4), 
	"TIER10_HIGH_VALUE" NUMBER(14,4), 
	 CONSTRAINT "REBATE_ITEM_QUALIFICATION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."RMA" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"END_CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_OID" NUMBER NOT NULL ENABLE, 
	"PROGRAM_OID" NUMBER NOT NULL ENABLE, 
	"ASSEMBLY_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_DISTI_FAE_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_SALES_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_MFR_FAE_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_CUST_ENG_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_CUST_CONTACT_OID" NUMBER NOT NULL ENABLE, 
	"PRO_ORDER_OID" NUMBER NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(80 CHAR), 
	"REASON" VARCHAR2(80 CHAR), 
	"STATUS" VARCHAR2(80 CHAR), 
	"FIRST_PART_OID" NUMBER NOT NULL ENABLE, 
	"TOTAL_QUANTITY" NUMBER NOT NULL ENABLE, 
	"TOTAL_COST" NUMBER(38,6) NOT NULL ENABLE, 
	"OFFSET_ORDERS" VARCHAR2(80 CHAR), 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "RMA_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."RMA_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"RMA_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(80 CHAR), 
	 CONSTRAINT "RMA_HISTORY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."RMA_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"RMA_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"RECEIVED_DATE" DATE, 
	"REPLACED_DATE" DATE, 
	"QUANTITY_TO_RETURN" NUMBER NOT NULL ENABLE, 
	"QUANTITY_PURCHASED" NUMBER NOT NULL ENABLE, 
	"UNIT_COST" NUMBER(38,6) NOT NULL ENABLE, 
	"TOTAL_COST" NUMBER(38,6) NOT NULL ENABLE, 
	"IS_ONLY_CREDIT" NUMBER NOT NULL ENABLE, 
	"ORDER_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"SO_NUM" VARCHAR2(80 CHAR), 
	"PO_NUM" VARCHAR2(80 CHAR), 
	"REMARKS" VARCHAR2(80 CHAR), 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) NOT NULL ENABLE, 
	"ALERT_FLAG" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "RMA_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."RMA_PF_ALERT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"RMA_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER NOT NULL ENABLE, 
	"ALERT_FLAG" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RMA_PF_ALERT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE, 
	 CONSTRAINT "RMA_PF_ALERT_UK1" UNIQUE ("RMA_OID", "PRODUCT_FAMILY_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."ROUTE_APPROVER_MAPPING" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"ROUTE_TRACKING_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"USER_ROLE_OID" NUMBER NOT NULL ENABLE, 
	"APPROVAL_STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DATE_SENT" DATE, 
	"DELEGATION_LEVEL" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "ROUTE_APPROVER_MAPPING_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."ROUTE_APPROVER_MAPPING_VER" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"ROUTE_TRACKING_OID" NUMBER NOT NULL ENABLE, 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"USER_ROLE_OID" NUMBER NOT NULL ENABLE, 
	"APPROVAL_STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DATE_SENT" DATE, 
	"DELEGATION_LEVEL" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ROUTE_APPROVER_MAPPING_VER_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."ROUTE_TRACKING" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_OID" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_GROUP_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_OID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_STEP_OID" NUMBER NOT NULL ENABLE, 
	"DISPLAY_NUM" VARCHAR2(80 CHAR), 
	"STEP_NUM" NUMBER NOT NULL ENABLE, 
	"STEP_NAME" VARCHAR2(80 CHAR), 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DATE_SENT" DATE, 
	"DATE_REVIEWED" DATE, 
	"REVIEWED_BY_OID" NUMBER NOT NULL ENABLE, 
	"WAIT_STEP_INDEX" NUMBER NOT NULL ENABLE, 
	"PARENT_OID" NUMBER NOT NULL ENABLE, 
	"STEP_INDEX" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"VERSION_NUM" NUMBER DEFAULT '1' NOT NULL ENABLE, 
	"SEND_BACK_COUNT" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"SENT_BACK_WF_STEP_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "ROUTE_TRACKING_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."ROUTE_TRACKING_VER" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_OID" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_TYPE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_GROUP_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_OID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"WORKFLOW_STEP_OID" NUMBER NOT NULL ENABLE, 
	"DISPLAY_NUM" VARCHAR2(80 CHAR), 
	"STEP_NUM" NUMBER NOT NULL ENABLE, 
	"STEP_NAME" VARCHAR2(80 CHAR), 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"DATE_SENT" DATE, 
	"DATE_REVIEWED" DATE, 
	"REVIEWED_BY_OID" NUMBER NOT NULL ENABLE, 
	"WAIT_STEP_INDEX" NUMBER NOT NULL ENABLE, 
	"PARENT_OID" NUMBER NOT NULL ENABLE, 
	"STEP_INDEX" NUMBER NOT NULL ENABLE, 
	"VERSION_NUM" NUMBER NOT NULL ENABLE, 
	"SEND_BACK_COUNT" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	"SENT_BACK_WF_STEP_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "ROUTE_TRACKING_VER_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."SALES_ORG_ADDRESS_MAPPING" 
   (	"ADDRESS_OID" NUMBER NOT NULL ENABLE, 
	"ORG_OID" NUMBER NOT NULL ENABLE, 
	"IS_PRIMARY" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SALES_ORG_ADDRESS_MAPPING_UK1" UNIQUE ("ADDRESS_OID", "ORG_OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."SEGMENT" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "SEGMENT_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."STOCK_ROTATION" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"DISTRIBUTOR_OID" NUMBER NOT NULL ENABLE, 
	"RMA_OID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"REVIEW_START" DATE, 
	"REVIEW_END" DATE, 
	"AMOUNT_ELIGIBLE" NUMBER(38,6) NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) DEFAULT '1' NOT NULL ENABLE, 
	 CONSTRAINT "STOCK_ROTATION_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."STOCK_ROTATION_ITEM" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"STOCK_ROTATION_OID" NUMBER NOT NULL ENABLE, 
	"PART_OID" NUMBER NOT NULL ENABLE, 
	"QOH_QTY" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"QTY_ELIGIBLE" NUMBER NOT NULL ENABLE, 
	"QTY_REQUESTED" NUMBER NOT NULL ENABLE, 
	"QTY_APPROVED" NUMBER NOT NULL ENABLE, 
	"REVIEW_FLAG" NUMBER NOT NULL ENABLE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,15) DEFAULT '1' NOT NULL ENABLE, 
	"CUSTOM_FIELD1" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD2" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD3" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD4" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD5" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD6" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD7" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD8" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD9" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD10" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD11" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD12" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD13" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD14" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD15" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD16" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD17" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD18" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD19" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD20" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD21" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD22" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD23" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD24" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD25" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD26" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD27" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD28" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD29" VARCHAR2(1024 CHAR), 
	"CUSTOM_FIELD30" VARCHAR2(1024 CHAR), 
	 CONSTRAINT "STOCK_ROTATION_ITEM_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."STOCK_ROTATION_ITEM_BUCKET" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"INVENTORY_BUCKET_OID" NUMBER NOT NULL ENABLE, 
	"STOCK_ROTATION_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER(38,6) NOT NULL ENABLE, 
	"IS_ELIGIBLE" NUMBER NOT NULL ENABLE, 
	"ELIGIBLE_QUANTITY" NUMBER NOT NULL ENABLE, 
	"SHIPMENT_DATE" DATE, 
	"CURRENCY_INFO_OID" NUMBER NOT NULL ENABLE, 
	"EXCHANGE_RATE" NUMBER(38,6) NOT NULL ENABLE, 
	"IS_INV_BUCKET_UPDATED" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "STOCK_ROTATION_ITEM_BUCKET_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."STOCK_ROTATION_ITEM_HISTORY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"STOCK_ROTATION_ITEM_OID" NUMBER NOT NULL ENABLE, 
	"TEXT" VARCHAR2(1024 CHAR) NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(1024 CHAR), 
	"PRO_USER_OID" NUMBER NOT NULL ENABLE, 
	"STOCK_ROTATION_OID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FAMILY_OID" NUMBER DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "STCK_RTTN_TM_HSTRY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";

CREATE TABLE "HT_REGRESSION_QA"."SUB_FAMILY" 
   (	"OID" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"MODIFIED_DATE" DATE, 
	"GUI_MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(80 CHAR), 
	"OBSOLETE_FLAG" NUMBER NOT NULL ENABLE, 
	"LIST_ORDER" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"SFDC_ID" VARCHAR2(80 CHAR), 
	"SF_CODE" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "SUB_FAMILY_PK" PRIMARY KEY ("OID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MN_DATA1";
